---
- name: Prepare metallb crs and deploy it to the first master
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
  run_once: true
  block:
  - name: Create manifests directory for temp configuration
    file:
      path: /tmp/metallb
      state: directory
      owner: "{{ ansible_user_id }}"
      mode: "0755"
    run_once: true
    with_items: "{{ groups[group_name_master | default('master')] }}"

  - name: Copy metallb CRs manifest to first master
    template:
      src: "metallb.crs.j2"
      dest: "/tmp/metallb/metallb-crs.yml"
      owner: "{{ ansible_user_id }}"
      mode: "0755"
    run_once: true
    with_items: "{{ groups[group_name_master | default('master')] }}"

  - name: Wait for metallb pods to be in Running state
    command: >-
      {{ kubectl_prefix }} kubectl wait --for=condition=ready pod -l app=metallb
      --namespace=metallb-system
      --timeout={{ metallb_available_timeout | default('300s') }}
    changed_when: false
    run_once: true
    retries: 5

  - name: Apply metallb CRs if not already applied
    command: >-
      {{ kubectl_prefix }} kubectl apply -f /tmp/metallb/metallb-crs.yml
      --timeout='{{ metallb_available_timeout }}'
    register: this
    changed_when: false
    run_once: true
    until: this.rc == 0
    retries: 5
