---
- name: Prepare flannel on first master and deploy flannel CNI
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
  run_once: true
  block:
  - name: Create manifests directory on first master
    file:
      path: "{{ manifest_path }}/"
      state: directory
      owner: root
      group: root
      mode: "0644"

  - name: Download flannel config to the first master
    ansible.builtin.get_url:
      url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
      dest: "{{ manifest_path }}/flannel-manifest.yaml"
      owner: root
      group: root
      mode: "0644"
