---
- name: Prepare kube-vip and deploy it on the first master
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
  run_once: true
  block:
  - name: Create manifests directory on first master
    file:
      path: "{{ manifest_path }}/"
      state: directory
      owner: root
      group: root
      mode: "0644"

  - name: Download vip rbac manifest to first master
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/kube-vip/kube-vip/{{ kube_vip_tag_version }}/docs/manifests/rbac.yaml"
      dest: "{{ manifest_path }}/vip-rbac.yaml"
      owner: root
      group: root
      mode: "0644"

  - name: Copy vip manifest to first master
    template:
      src: "vip.yaml.j2"
      dest: "{{ manifest_path }}/vip.yaml"
      owner: root
      group: root
      mode: "0644"
