---
- name: Prepare kube-vip load balancer and deploy on first master
  when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
  run_once: true
  block:
  - name: Create manifests directory for temp configuration
    file:
      path: /tmp/kube-vip-cp
      state: directory
      owner: "{{ ansible_user_id }}"
      mode: "0755"

  - name: Copy kube-vip-cp-pool CRs manifest to first master
    template:
      src: "kube-vip-cp-configmap.j2"
      dest: "/tmp/kube-vip-cp/kube-vip-cp-configmap.yaml"
      owner: "{{ ansible_user_id }}"
      mode: "0755"

  - name: Wait for kube-vip-cp pods to be in Running state
    command: >-
      {{ kubectl_prefix }} kubectl wait --for=condition=ready pod -l app=kube-vip
      --namespace=kube-system
      --timeout={{ kube_vip_lb_available_timeout | default('300s') }}

  - name: Apply kube-vip-cp CRs if not already applied
    command: >-
      {{ kubectl_prefix }} kubectl apply -f /tmp/kube-vip-cp/kube-vip-cp-configmap.yaml
      --timeout='{{ kube_vip_lb_available_timeout }}'
    register: this
    changed_when: false
    until: this.rc == 0
    retries: 5
